version: '3.8'

services:
  benchmark:
    image: ${BENCHMARK_IMAGE}
    volumes:
      - /tmp/Results:/tmp/Results
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: all
              capabilities: [gpu]
  
  gpu_monitor:
    image: gpu_monitor
    volumes:
      - ./results:/app/results
    tty: true
    entrypoint: ["/bin/sh", "-c", "${COMMAND}"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: all
              capabilities: [gpu]





